services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.87.0
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      # OTLP
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      # Observability / health
      - "8888:8888"     # Internal Collector metrics (Prometheus scrape)
      - "8889:8889"     # External Collector metrics (Prometheus scrape)
      - "13133:13133"   # Health check
      - "55679:55679"   # zPages
    depends_on:
      - jaeger
      - loki
    networks:
      - otel

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"   # Zipkin compatible
    networks:
      - otel

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=2d"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
    networks:
      - otel

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    networks:
      - otel

  loki:
      image: grafana/loki:latest
      container_name: loki
      volumes:
        - ./loki-config.yaml:/etc/loki/config.yaml
      command: -config.file=/etc/loki/config.yaml
      ports:
        - "3100:3100"  
      networks:
        - otel

networks:
  otel:
    driver: bridge
